# Generated by Django 4.1.7 on 2023-03-31 07:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APP_Users_Login', '0002_userinfo_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='chat_id', primary_key=True, serialize=False)),
                ('openai_params', models.TextField(help_text='openai_params')),
                ('chat_summary', models.CharField(help_text='chat_summary', max_length=200)),
                ('chat_message', models.TextField(help_text='chat_message')),
                ('is_deleted', models.BooleanField(default=False, help_text='is_deleted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='updated_at')),
                ('user_id', models.ForeignKey(help_text='user_id', on_delete=django.db.models.deletion.CASCADE, to='APP_Users_Login.userinfo')),
            ],
        ),
    ]
