# Generated by Django 4.1.7 on 2023-03-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_User_Operate', '0002_alter_chatinfo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='chat_message',
            field=models.JSONField(help_text='chat_message'),
        ),
        migrations.AlterField(
            model_name='chatinfo',
            name='openai_params',
            field=models.JSONField(help_text='openai_params'),
        ),
    ]
