# Generated by Django 4.1.7 on 2023-03-30 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(help_text='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='username', max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='is_active')),
                ('is_staff', models.BooleanField(default=False, help_text='is_staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='date_joined')),
                ('last_login', models.DateTimeField(blank=True, help_text='last_login', null=True)),
                ('token', models.CharField(blank=True, help_text='token', max_length=200, null=True)),
            ],
        ),
    ]
